### ISSUE TITLE
childprocess needs a new maintainer

### ISSUE THREAD

**Issue by jarib** [jarib/childprocess#104]
I'm unfortunately no longer able to maintain this gem. I'll be happy to move the repo and hand the Rubygems keys over to someone qualified who wants to take it over.

Please comment if you're interested.

I'll mention a few people who maintain popular dependent gems:

@mitchellh (vagrant)
@titusfortner / @p0deje (selenium-webdriver)
@dg-ratiodata (aruba)
@xrkhill (guard-spork)

**Comment by dg-ratiodata** [comment]
What a pitty! Thanks for maintaining it for so long. Will consider to take over maintainership. Can we have a chat/discussion about that? I need a bit more information to see what workload I'll get on top.

@mattwynne @aslakhellesoy Do you know somebody from the "cucumber"-org who might be interested in this?

**Comment by aslakhellesoy** [comment]
I don't know who it might be - I have too much on my plate already.

**Comment by mattwynne** [comment]
Try @dg-ratiodata

**Comment by jarib** [comment]
@dg-ratiodata Great that you're interested. 

The library is pretty stable. My latest commit is from January. There's a few issues reported on Windows, and they can be a bit hard to track down. Otherwise it's mostly about handling the occasional pull request, and making sure we don't break platform parity by introducing new, platform-specific APIs.

Happy to have a chat on IRC/Slack/Skype if you want to.

**Comment by dg-ratiodata** [comment]
@jarib Haven't had a look that the issues... I'm not an active windows user for development. This might be a problem. :-/

**Comment by jarib** [comment]
I'm not really either. It's still useful to have someone triage issues and do code reviews, even though Windows fixes will have to come from that community.

**Comment by dg-ratiodata** [comment]
@jarib First I could take over maintainership, but unfortunately I don't have much time to work on aruba either which is my first priority. So it would be not "healthy" for childprocess to say "yes". Hope someone else steps in. Sorry. 

But what about asking for help on http://www.rubyflow.com/? Maybe we/you could even ask Peter Cooper to include this request in his weekly newsletter? @jarib What do you think?

**Comment by enkessler** [comment]
I might be able to help out with it.

I may not be much of a consumer of the gem, but I think that I understand the concept of the thing and it is interesting. The code looks clean, the documentation is decent enough and there is a test framework in place. I'm game enough to give it a try.

**Comment by dg-ratiodata** [comment]
@enkessler Great! Thanks a lot.

**Comment by jarib** [comment]
@enkessler That's great! Let me get my ducks in a row and I'll hand over the keys to you.

**Comment by mattwynne** [comment]
👍 🎉 🎈 nice one @enkessler thank you! This gem is an important part of the Cucumber ecosystem.

**Comment by enkessler** [comment]
Thanks, all. This will be the first gem that I've had to work with (as a maintainer instead of a normal contributor) that appears to have any sort of popularity. The experience should be interesting.

**Comment by mattwynne** [comment]
We're all here to help you @enkessler - give me a shout anytime if you need to talk anything through.

**Comment by enkessler** [comment]
@mattwynne Much appreciated.

**Comment by jarib** [comment]
@enkessler I've initiated the repo transfer and added you as a gem owner. Don't hesitate to ask if you have any questions, now or in the future.
