### ISSUE TITLE
[Windows] Improper quoting of parameters

### ISSUE THREAD

**Issue by jawshooah** [jarib/childprocess#86]
A [common method](http://blogs.msdn.com/b/oldnewthing/archive/2011/08/25/10200026.aspx) of counting the number of lines in a file in Windows batch is to use the command `find /c /v "" some-file`. I tried this using `ChildProcess.build`, since I need a Windows equivalent to `wc -l` for compatibility. Here were the results:

```
irb(main):001:0> require 'childprocess'
=> true
irb(main):002:0> process = ChildProcess.build(*%w[find /c /v "" some-file])
=> #<ChildProcess::Windows::Process:0x00000002bd75e8 @args=["find", "/c", "/v", "\"\"", "some-file"], @started=false, @exit_code=nil, @io=nil, @cwd=nil, @detach=false, @duplex=false, @leader=false, @environment={}>
irb(main):003:0> process.io.inherit!
=> #<IO:<STDERR>>
irb(main):004:0> process.start
=> #<ChildProcess::Windows::Process:0x00000002bd75e8 @args=["find", "/c", "/v", "\"\"", "some-file"], @started=true, @exit_code=nil, @io=#<ChildProcess::Windows::IO:0x00000002bedaf0 @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>>, @cwd=nil, @detach=false, @duplex=false, @leader=false, @environment={}, @pid=192, @handle=#<ChildProcess::Windows::Handle:0x00000002348bc0 @pid=192, @pointer=#<FFI::Pointer address=0x0000000000009c>, @closed=false>>
irb(main):005:0> FIND: Parameter format not correct
```

The problem is that the `""` parameter is being quoted as `'""'` by `ChildProcess::Windows::ProcessBuilder#quote_if_necessary`. Single-quotes aren't treated as string delimiters in batch, so this doesn't work.

Why was this quoting introduced in the first place? I imagine it must break plenty of other use cases as well.

**Comment by jarib** [comment]
You're not running a batch script, you're sending arguments to the find executable directly through `CreateProcess`. The quoting behaviour was introduced to ensure the spec in [this PR](https://github.com/jarib/childprocess/pull/9) passes. 

If you want shell behaviour, see my suggestion in #85, which should solve your issue.
