### ISSUE TITLE
process.stop no method error 

### ISSUE THREAD

**Issue by vkyt** [jarib/childprocess#87]
I've been receiving the following error when calling the process.stop method on the childprocess instance.

Here's how I'm using it:
Inside my ProcessHelper class, I have two methods, start and stop. I'm calling them to start a server in the background and run some tests.  When I'm down with my tests I need to shut down the process.

def start
process = ChildProcess.build(*parameters)
process.start
end

#doing something with the process running in background

def stop
process.stop 
#need to stop the process explicitly since it does not exit on its own so wait will not work
end

**The error I'm getting is:**
 undefined method `stop' for # < ProcessHelper:0x007fd29555d5b0 @ params=["appium"]> (NoMethodError)

**Comment by jarib** [comment]
The exception you've included indicates that ProcessHelper doesn't have a `stop` instance method. If you believe it's a bug in ChildProcess, please provide a full example with all the code necessary to reproduce the problem.
