### ISSUE TITLE
Strange "Command not found"-error.

### ISSUE THREAD

**Issue by maxmeyer** [jarib/childprocess#89]
We see some of our tests failing with jruby:

~~~
     Failure/Error: before(:each) { run(cmd) }
     Aruba::LaunchError:
       Cannot run program "cmd.sh" (in directory "/home/user/data/projects/aruba/tmp/aruba"): error=2, No such file or directory
~~~

We're using `ChildProcess` in [`aruba`](https://github.com/cucumber/aruba) to run shell commands with this peace of code:

~~~ruby
      def start
        @process     = ChildProcess.build(command, *arguments)
        @stdout_file = Tempfile.new("aruba-stdout")
        @stderr_file = Tempfile.new("aruba-stderr")
        @exit_status = nil
        @duplex      = true

        before_run

        @process.io.stdout = @stdout_file
        @process.io.stderr = @stderr_file
        @process.duplex    = @duplex
        @process.cwd       = @working_directory

        @process.environment.update(environment)

        begin
          with_local_env(environment) do
            @process.start
          end
        rescue ChildProcess::LaunchError => e
          raise LaunchError, e.message
        end
~~~

The `#with_environment`-methods has the following code:

~~~ruby
def with_environment(env = {}, &block)
  if RUBY_VERSION <= '1.9.3'
    old_env = ENV.to_hash.dup
  else
    old_env = ENV.to_h.dup
  end

  old_aruba_env = aruba.environment.to_h

  ENV.update aruba.environment.update(env).to_h

  block.call if block_given?
ensure
  ENV.clear
  ENV.update old_env
end
~~~

If we run our build on Travis with `mri`-rubies everything is fine, but with `jruby` (1.7.x, 9000) it fails:
https://travis-ci.org/cucumber/aruba/jobs/72323854#L1088

Looking at your sources, [line 77](/home/d/.gem/jruby/gems/childprocess-0.5.6/lib/childprocess/jruby/process.rb:77) seems to cause the trouble. Running `pb.start` before `pb.environment` is invoked works. After `pb.environment` was called it failes. I see no difference within ENV and `Dir.getwd`:

~~~
[1] pry(#<ChildProcess::JRuby::Process>)> Dir.getwd
=> "/home/user/data/projects/aruba"
[2] pry(#<ChildProcess::JRuby::Process>)> ENV['PATH']
=> "/home/user/data/projects/aruba/tmp/aruba:/home/user/data/projects/aruba/bin:/home/user/.gem/jruby/bin:/home/user/.gem/2.2.2/bin:/home/user/.local/share/npm/bin:/home/user/.local/share/golang/bin:/home/user/.local/share/go/bin:/home/user/bin:/home/user/.gem/ruby/2.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/.rvm/bin"
~~~

But it seems to me, that some Java-code is involved. Unfortunately I've no experience how to debug jruby java code. Maybe you can have a look into it?

1. Clone `aruba` repository, https://github.com/cucumber/aruba
2. `bundle install`
3.  `jruby /home/user/.gem/jruby/bin/rspec ./spec/aruba/matchers/command_spec.rb:128`

BTW:
This is how I run the rspec command on my local machine. Where it fails as well:

~~~bash
JRUBY_OPTS='--dev' GEM_HOME=~/.gem/jruby GEM_PATH=~/.gem/jruby GEM_ROOT=~/.gem/jruby jruby /home/user/.gem/jruby/bin/rspec ./spec/aruba/matchers/command_spec.rb:128
~~~

Thanks a lot.

@mattwynne Ping.

**Comment by maxmeyer** [comment]
Matt, maybe you've got an idea what's wrong here. The error occures when I ran cucumber with code in this branch https://github.com/dg-ratiodata/aruba/tree/feature/improve_documentation.

**Comment by maxmeyer** [comment]
@jarib Any idea what's wrong? Did I do something wrong in the code?

**Comment by jarib** [comment]
I don't see anything obviously wrong, but two things to try:

1. Does it work if you try to execute the script with ChildProcess directly, outside Aruba?
2. Is `cmd.sh` executable? It shouldn't be different on MRI, but worth checking.

If you can provide a standalone script that reproduces the problem, I'll have a look.

**Comment by dg-ratiodata** [comment]
@jarib I could reproduce the error without `aruba`. It seems to be somehow related to run `childprocess` under `bundle exec` + having `gemspec` in your `Gemfile` + `jruby`. Totally strange.

I put together a "showcase" you can find here https://github.com/dg-ratiodata/childprocess-issue-bundler. There's also a README.md in the repository.

**Comment by dg-ratiodata** [comment]
I'm not sure what happens in the code and how this is related to bundler.

**Comment by dg-ratiodata** [comment]
The problem occures with jruby 9000 as well: jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 OpenJDK 64-Bit Server VM 24.85-b03 on 1.7.0_85-b01 +jit [linux-amd64]

**Comment by dg-ratiodata** [comment]
Another information I can share with you. If you add the following code snippet to the [`script/meta.sh`](https://github.com/dg-ratiodata/childprocess-issue-bundler/blob/master/script/meta.sh), each script succeeds:

~~~bash
export PATH="${PWD}/case1/tmp:$PATH"
export PATH="${PWD}/case2/tmp:$PATH"

cd case1
echo '########'
echo '### Bootstrap case1'
echo '########'
# [...]
~~~

If you modify PATH from within a ruby script "only" it fails for jruby, e.g. https://github.com/dg-ratiodata/childprocess-issue-bundler/blob/master/case1/tmp/test.rb#L5

**Comment by dg-ratiodata** [comment]
Maybe this is the same problem within some java code http://stackoverflow.com/questions/10035383/setting-the-environment-for-processbuilder

**Comment by jarib** [comment]
Ah, I see. So there's something related to the PATH modification. I couldn't even get your `success.sh` script to work. This is sufficient to reproduce the problem on my machine:

```ruby
require 'tmpdir'
require 'childprocess'

path = Dir.mktmpdir
File.open(File.join(path, 'test.sh'), 'w') do |io|
  io << "#!/bin/bash\necho hello world"
  io.chmod(0755)
end

ENV['PATH'] = "#{path}:#{ENV['PATH']}"

proc = ChildProcess.build('test.sh')
proc.io.inherit!
proc.start
proc.wait
```

**Comment by jarib** [comment]
The problem seems to be that modifications to `ENV["PATH"]` isn't reflected in the Java env:

```ruby
ENV["PATH"] = "/foo:#{ENV["PATH"]}"
java.lang.System.getenv("PATH").include?("/foo:") #=> false
```

This looks like a bug in JRuby to me.

**Comment by maxmeyer** [comment]
Can you help me to put together an issue for the jruby guys or even file the issue? I'm to far away from java.

**Comment by maxmeyer** [comment]
Thanks a lot for your help! I created an issue at jruby.

**Comment by kares** [comment]
please note that by design `java.lang.System.getenv` in read-only on the JVM level, thus that will never work (when using `ProcessBuilder`), however a thing to try would be doing the Unix way on JRuby 9.0.0.0

**Comment by dg-ratiodata** [comment]
> however a thing to try would be doing the Unix way on JRuby 9.0.0.0

Can you elaborate on this a bit? What would be the "Unix way on JRuby 9.0.0.0"?

> please note that by design java.lang.System.getenv in read-only on the JVM level, thus that will never work (when using ProcessBuilder), 

Just to make this clear (to me)
* Design by Java?
* Design by JRuby?

> in read-only on the JVM level

Ok. So this "cannot" / will not be fixed and we at cucumber/aruba and/or @jarib need to work around this?

Thanks a lot.

**Comment by jarib** [comment]
@kares  JRuby 9000 doesn't support `fork()`, so the Unix way isn't really an option.

That said, I tried reproducing this in JRuby 9000, and my test script above works fine (with the `ProcessBuilder` code path) even though `ENV["PATH"]` isn't changed. No idea what's going on there.

This problem can be worked around for any JRuby version **on Unix** by setting `ChildProcess.posix_spawn = true` (or `CHILDPROCESS_POSIX_SPAWN=1` in the environment)

That should be a sufficient workaround this issue. I don't want PATH searching in childprocess.

**Comment by maxmeyer** [comment]
@jarib What would be a suitable workaround on Windows? PATH search, as we already do? 

Would you mind to add a "warning" to the README, so that other users are aware of this?

**Comment by jarib** [comment]
@maxmeyer childprocess doesn't use `ProcessBuilder` on Windows, so this shouldn't be an issue there.
