### ISSUE TITLE
[cygwin] When setting the leader property of the process instance to true I'm not able to obtain an exit code

### ISSUE THREAD

**Issue by Elpaggio** [jarib/childprocess#91]
I have found a problem when using the childprocess gem on cygwin platform with
ruby 2.0.0p598 (2014-11-13) [i386-cygwin].
$ uname -a
CYGWIN_NT-6.1 lapa-PC 2.0.1(0.287/5/3) 2015-04-30 18:13 i686 Cygwin

Below is a pry session demonstration:

[8] pry(main)> process = ChildProcess.build("echo", "foo")
<ChildProcess::Unix::ForkExecProcess:0x20558244 @args=["echo", "foo"], @started=false, @exit_code=nil, @io=nil, @cwd=nil, @detach=false, @duplex=false, @leader=false, @environment={}>
[9] pry(main)> process.leader = true
true
[10] pry(main)> process.start
<ChildProcess::Unix::ForkExecProcess:0x20558244 @args=["echo", "foo"], @started=true, @exit_code=nil, @io=nil, @cwd=nil, @detach=false, @duplex=false, @leader=true, @environment={}, @pid=8128>
[11] pry(main)> process.wait
nil
[12] pry(main)> process.exit_code
nil

Below example works fine when leader property is not set to true
---------------------------------------------------------------------------------------------------------
[13] pry(main)> process = ChildProcess.build("echo", "foo")
<ChildProcess::Unix::ForkExecProcess:0x207876b4 @args=["echo", "foo"], @started=false, @exit_code=nil, @io=nil, @cwd=nil, @detach=false, @duplex=false, @leader=false, @environment={}>
[14] pry(main)> process.start
<ChildProcess::Unix::ForkExecProcess:0x207876b4 @args=["echo", "foo"], @started=true, @exit_code=nil, @io=nil, @cwd=nil, @detach=false, @duplex=false, @leader=false, @environment={}, @pid=4720>
[15] pry(main)> process.wait
0
[16] pry(main)>

**Comment by jarib** [comment]
I don't have a Cygwin setup to debug this on myself.

Is the problem here that 

* (a) the process doesn't start, or that (b) the result of `#exit_code` is nil?

You could try setting `ChildProcess.posix_spawn = true` before creating the process and see if that helps.

**Comment by Elpaggio** [comment]
a) The process starts fine and exits without any errors
b) and yes the exit_code is nil

I tried setting "ChildProcess.posix_spawn = true" but received an error for the childprocess library.

$ pry
[1] pry(main)> require 'childprocess'
true
[2] pry(main)> ChildProcess.posix_spawn = true
true
[3] pry(main)> process = ChildProcess.build("echo", "foo")
posix_spawn is not yet supported on i386-cygwin (i386-cygwin), falling back to default implementation. If you believe this is an error, please file a bug at http://github.com/jarib/childprocess/issues

Maybe this could be a ruby problem with the Process.wait2 method on Cygwin.

**Comment by jarib** [comment]
We could try to add `posix_spawn` support for cygwin, if you could:

1. Clone this repo
2. Run `bundle install && rake generate`
3. Create a pull request with the generated file (should be `lib/childprocess/unix/platform/i386-cygwin.rb`
