### ISSUE TITLE
Handle spaces in options on windows

### ISSUE THREAD

**Issue by titusfortner** [jarib/childprocess#92]
I'm passing the following in on Windows, but it is failing by not putting the quotes around the path, and I don't see how they can be escaped: 

```Ruby
ChildProcess.build("C:/drivers/wires", "--binary C:/Program Files (x86)/Nightly/firefox.exe")
```

**Comment by titusfortner** [comment]
Finally found something that I can at least do some string manipulation with.
```
'--binary="\"C:\Progra~2\Nightly\firefox.exe"'
```

**Comment by jarib** [comment]
Each argument to the program should be an argument to `ChildProcess.build`. I'd try this:

```ruby
ChildProcess.build("C:\\drivers\\wires", "--binary", "C:\\Program Files (x86)\\Nightly\\firefox.exe")
```

Noe that childprocess isn't executing the program through a shell (on any platform). If you need shell behaviour, you should do that yourself, i.e.:

```ruby
ChildProcess.build("cmd.exe", "/c", "C:\\drivers\\wires --binary C:\\Program Files (x86)\\Nightly\\firefox.exe")
```
