### ISSUE TITLE
Add ability to set process user id (`setuid`)

### ISSUE THREAD

**Issue by yagudaev** [jarib/childprocess#95]
I think it is really important to be able to se the user who is running the child process in cases where you would like a less privileged user running the code.

Ruby has support for this through the [Process class called uid](http://ruby-doc.org/core-2.1.1/Process.html#method-c-uid-3D). Is there a way to get the corresponding Process from ChildProcess now?

**Comment by jarib** [comment]
We don't use the `Process` class under the hood, so no. 

I don't think this will be possible to implement cross platform, and that's the whole point of childprocess. I'm not going to expand the API to include features that are only available on some platforms. 

That being said, feel free to prove me wrong in a PR.
