### ISSUE TITLE
Ability to stop a detached child process

### ISSUE THREAD

**Issue by hferentschik** [jarib/childprocess#97]
I am basically trying to figure out how to stop a child process, if it is detached from the parent?
I cannot call `Process.stop` since I don't have a handle to the Process instance anymore. One would need a way to somehow create a Process from a pid. So maybe this is related to #57?

I tried to use `Process.pid` and save it to a pidfile and then stop/kill the process via

     ...
     pgid = -Process.getpgid(pid)
     Process.kill("INT", pgid)
     ...

This works fine for Linux, but won't work on Windows, since there `Process.getpgid` is not implemented.
What would I do on Windows or am I missing something obvious?

**Comment by hferentschik** [comment]
@jarib any ideas?

**Comment by jarib** [comment]
Not really sure how to do exactly what you're asking on Windows. 

One solution would be to not detach from the process until right before your program exits. Childprocess only provides a way to control detachment before launching the process, but you could still use `Process.detach` to detach later (presumably also on Windows).

Detaching from a process is basically telling the process "I don't care about you from now on". If you need to kill it later, that means you still care and shouldn't have detached from it.

**Comment by jarib** [comment]
Stopping a detached process is not something we're going to support, so I'm closing this.

**Comment by hferentschik** [comment]
I am a bit surprised you closed the issue as something which childprocess won't support. Some comments below:

> Not really sure how to do exactly what you're asking on Windows. 

Using plain Ruby, this is what works on Windows

    pid = spawn(" ruby #{__FILE__} run", :chdir=>Dir.pwd, :new_pgroup=>true)

This will spawn a detached process on Windows and returns its pid. This pid can then even be killed via `Process#kill`. So I would expect that childprocess basically under the covers does something along these lines

>  but you could still use Process.detach to detach later (presumably also on Windows).

I think detaching is broken in general on Windows. See issue #99.

> Detaching from a process is basically telling the process "I don't care about you from now on". If you need to kill it later, that means you still care and shouldn't have detached from it. 

What's about a daemon process then. There a parent process creates the daemon and then continues or even exits and the process is supposed to run until explicitly stopped. Daemon process are a common thing, at least on Unix. I guess on Windows the "preferred" way might be to create a Windows Service, but that means that your code looks very different for Unix and Windows. On the former OS you would create a daemon and control the daemon via the stored pid, while on Windows one would need to create and configure a Windows Service and start/stop it (potentially even removing it). I think the pid approach can work on Windows as well and having a library like childprocess offering a shared API to handle the differences between Unix and Windows would be nice. However, you seem to see this differently.
